services:
  evidencedb:
    container_name: evidencedb
    read_only: true
    build:
      context: .
      target: production
    restart: always
    user: ${PUID}:${PGID}
    networks:
      - evidencedb
    environment:
      - TZ=${TZ}
      - MONGO_URL=${MONGO_URL}
      - CDN=${CDN}
      - NODE_PORT=${NODE_PORT}
      - JS_VER=${JS_VER}
      - CSS_VER=${CSS_VER}
      - GTM_ID=${GTM_ID}
      - DEFAULT_IMAGE=${DEFAULT_IMAGE}
      - OFFENDER_NAME=${OFFENDER_NAME}
      - PAGE_TITLE=${PAGE_TITLE}
      - DEV_BASE_URL=${DEV_BASE_URL}
      - PROD_BASE_URL=${PROD_BASE_URL}
      - STATS_URL=${STATS_URL}
      - PAGE_DESCRIPTION=${PAGE_DESCRIPTION}
      - DEFAULT_DATE_PUBLISHED=${DEFAULT_DATE_PUBLISHED}
      - OFFENDER_ADDRESS=${OFFENDER_ADDRESS}
      - OFFENDER_CITY=${OFFENDER_CITY}
      - OFFENDER_STATE=${OFFENDER_STATE}
      - OFFENDER_ZIP=${OFFENDER_ZIP}
      - OFFENDER_PHONES=${OFFENDER_PHONES}
      - OFFENDER_URL=${OFFENDER_URL}
      - OFFENDER_ALT_URLS=${OFFENDER_ALT_URLS}
      - OFFENDER_ALT_NAMES=${OFFENDER_ALT_NAMES}
      - OFFENDER_EMAILS=${OFFENDER_EMAILS}
    tmpfs:
      - /tmp:rw,noexec,nosuid,uid=${PUID},gid=${PGID}
    logging:
      driver: syslog
      options:
        syslog-address: udp://192.168.22.11:514
        tag: texts-nginx
        syslog-format: rfc5424
    deploy:
      resources:
        limits:
          cpus: "10"
          pids: 300
          memory: 500M
    security_opt:
      - no-new-privileges=true

  evidencedb-dev:
    container_name: evidencedb-dev
    read_only: true
    build:
      context: ./
      target: development
      args:
        - NODE_ENV=development
    restart: always
    user: ${PUID}:${PGID}
    networks:
      - evidencedb
    expose:
      - ${NODE_PORT}
    environment:
      - TZ=${TZ}
      - MONGO_URL=${MONGO_URL}
      - CDN=${CDN}
      - NODE_PORT=${NODE_PORT}
      - CSS_VER=${CSS_VER}
      - JS_VER=${JS_VER}
      - GTM_ID=${GTM_ID}
      - DEFAULT_IMAGE=${DEFAULT_IMAGE}
      - OFFENDER_NAME=${OFFENDER_NAME}
      - PAGE_TITLE=${PAGE_TITLE}
      - DEV_BASE_URL=${DEV_BASE_URL}
      - PROD_BASE_URL=${PROD_BASE_URL}
      - STATS_URL=${STATS_URL}
      - PAGE_DESCRIPTION=${PAGE_DESCRIPTION}
      - DEFAULT_DATE_PUBLISHED=${DEFAULT_DATE_PUBLISHED}
      - OFFENDER_ADDRESS=${OFFENDER_ADDRESS}
      - OFFENDER_CITY=${OFFENDER_CITY}
      - OFFENDER_STATE=${OFFENDER_STATE}
      - OFFENDER_ZIP=${OFFENDER_ZIP}
      - OFFENDER_PHONES=${OFFENDER_PHONES}
      - OFFENDER_URL=${OFFENDER_URL}
      - OFFENDER_ALT_URLS=${OFFENDER_ALT_URLS}
      - OFFENDER_ALT_NAMES=${OFFENDER_ALT_NAMES}
      - OFFENDER_EMAILS=${OFFENDER_EMAILS}
    volumes:
      - ./:/app
    tmpfs:
      - /tmp:rw,noexec,nosuid,uid=${PUID},gid=${PGID}
    logging:
      driver: syslog
      options:
        syslog-address: udp://192.168.22.11:514
        tag: texts-nginx
        syslog-format: rfc5424
    deploy:
      resources:
        limits:
          cpus: "10"
          pids: 300
          memory: 750M
    security_opt:
      - no-new-privileges=true
