services:
  evidencedb:
    container_name: evidencedb
    read_only: true
    build:
      context: .
      target: production
    restart: always
    user: ${PUID}:${PGID}
    networks:
      - proxy
      - mongodb
    expose:
      - ${NODE_PORT}
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.evidencedb.rule=Host(`texts.lloydnet.org`)
      - traefik.http.routers.evidencedb.entrypoints=https
      - traefik.http.routers.evidencedb.tls=true
      - traefik.http.routers.evidencedb.middlewares=public@file
    tmpfs:
      - /tmp:rw,noexec,nosuid,uid=${PUID},gid=${PGID}
    logging:
      driver: syslog
      options:
        syslog-address: udp://192.168.22.11:514
        tag: texts-nginx
        syslog-format: rfc5424
    deploy:
      resources:
        limits:
          cpus: "10"
          pids: 300
          memory: 500M
    security_opt:
      - no-new-privileges=true

  evidencedb-dev:
    container_name: evidencedb-dev
    read_only: true
    env_file:
      - ../.env
      - .env
    build:
      context: ./
      target: development
      args:
        - NODE_ENV=development
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.evidencedb-dev.entrypoints=https
      - traefik.http.routers.evidencedb-dev.tls=true
      - traefik.http.routers.evidencedb-dev.middlewares=default@file
    restart: always
    user: ${PUID}:${PGID}
    networks:
      - evidencedb
    expose:
      - ${NODE_PORT}
    volumes:
      - ./:/app
    tmpfs:
      - /tmp:rw,noexec,nosuid,uid=${PUID},gid=${PGID}
    deploy:
      resources:
        limits:
          cpus: "10"
          pids: 300
          memory: 750M
    security_opt:
      - no-new-privileges=true
